
CREATE TABLE Gerente (
    idGerente number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descGerente VARCHAR2(255) NOT NULL,
    FechaRegistro VARCHAR2(255) DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD')
);

CREATE TABLE Condicion (
    idCondicion number GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descCondicion VARCHAR2(255) NOT NULL,
    FechaRegistro VARCHAR2(255) DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD')
);

CREATE TABLE Provincia (
    idProvincia NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descProvincia VARCHAR2(255) NOT NULL,
    FechaRegistro VARCHAR2(255) DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD')
);

CREATE TABLE Sede (
    idSede NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descSede VARCHAR2(255) NOT NULL,
    FechaRegistro VARCHAR2(255) DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD')
);

CREATE TABLE Distrito (
    idDistrito NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    descDistrito VARCHAR2(255) NOT NULL,
    idProvincia NUMBER NOT NULL,
    FechaRegistro VARCHAR2(255) DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD'),
    CONSTRAINT fkProvincia FOREIGN KEY (idProvincia) REFERENCES Provincia(idProvincia)
);

CREATE TABLE Hospital (
    idHospital NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(255) NOT NULL,
    Antiguedad NUMBER NOT NULL,
    Area NUMBER(10,2) NOT NULL,
    FechaRegistro VARCHAR2(255) DEFAULT TO_CHAR(SYSDATE, 'YYYY-MM-DD'),
    idDistrito NUMBER NOT NULL,
    idSede NUMBER NOT NULL,
    idGerente NUMBER NOT NULL,
    idCondicion NUMBER NOT NULL,
    CONSTRAINT fkDistrito FOREIGN KEY (idDistrito) REFERENCES Distrito(idDistrito),
    CONSTRAINT fkSede FOREIGN KEY (idSede) REFERENCES Sede(idSede),
    CONSTRAINT fkGerente FOREIGN KEY (idGerente) REFERENCES Gerente(idGerente),
    CONSTRAINT fkCondicion FOREIGN KEY (idCondicion) REFERENCES Condicion(idCondicion)
);

INSERT INTO Gerente (descGerente) VALUES ('Benry');
INSERT INTO Gerente (descGerente) VALUES ('Jose');
INSERT INTO Condicion (descCondicion) VALUES ('Abierto');
INSERT INTO Condicion (descCondicion) VALUES ('Cerrado');
INSERT INTO Condicion (descCondicion) VALUES ('Emergencia');
INSERT INTO Provincia (descProvincia) VALUES ('Lima');
INSERT INTO Provincia (descProvincia) VALUES ('La libertad');
INSERT INTO Provincia (descProvincia) VALUES ('Ayacucho');
INSERT INTO Provincia (descProvincia) VALUES ('Piura');
INSERT INTO Sede (descSede) VALUES ('Principal');
INSERT INTO Sede (descSede) VALUES ('sucursal');
INSERT INTO Distrito (descDistrito, idProvincia) VALUES ('Trujillo', 2);
INSERT INTO Distrito (descDistrito, idProvincia) VALUES ('Huanchaco', 2);
INSERT INTO Distrito (descDistrito, idProvincia) VALUES ('Catacaos', 4);
INSERT INTO Distrito (descDistrito, idProvincia) VALUES ('Piuras', 4);

